import React, { createContext, useState } from 'react'

export const MyContext = createContext()

function Myprovider({ children }) {
    const [temp, setTemp] = useState(0)

    // Product Categories
    const categories = [
        'Pharmaceutical Raw Materials',
        'Food Additives',
        'Chemical Compounds',
        'Nutraceuticals',
        'Industrial Chemicals'
    ]

    // Comprehensive Product Data
    const productsData = [
        // Pharmaceutical Raw Materials
        {
            id: 1,
            name: "MICRO CRYSTALLINE CELLULOSE IP",
            category: "Pharmaceutical Raw Materials",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Ankit Pulps & Boards Pvt. Ltd./NB Entrepreneurs/Accent Microcell",
            price: 145,
            originalPrice: 165,
            discountPercentage: 12,
            inStock: true,
            stockQuantity: 150,
            description: "High-quality microcrystalline cellulose for pharmaceutical tablets and capsules manufacturing.",
            specifications: ["IP Grade", "Pharmaceutical Grade", "25kg packaging"],
            applications: ["Tablet binding", "Disintegrant", "Filler"],
            shelfLife: "36 months",
            storageConditions: "Store in cool, dry place"
        },
        {
            id: 2,
            name: "SODIUM BENZOATE",
            category: "Food Additives",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_bag.svg",
            manufacturer: "Navyug Pharma Pvt. Ltd.",
            price: 89,
            originalPrice: 105,
            discountPercentage: 15,
            inStock: true,
            stockQuantity: 200,
            description: "Food grade sodium benzoate preservative for beverages and food products.",
            specifications: ["Food Grade", "E211", "99% purity"],
            applications: ["Food preservative", "Beverage preservation", "Cosmetics"],
            shelfLife: "24 months",
            storageConditions: "Store in cool, dry place away from moisture"
        },
        {
            id: 3,
            name: "MAIZE STARCH",
            category: "Food Additives",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "PJCL Ltd.",
            price: 65,
            originalPrice: 75,
            discountPercentage: 13,
            inStock: true,
            stockQuantity: 300,
            description: "Pure maize starch for food processing and pharmaceutical applications.",
            specifications: ["Food Grade", "Non-GMO", "Gluten-free"],
            applications: ["Food thickening", "Tablet binder", "Textile sizing"],
            shelfLife: "24 months",
            storageConditions: "Store in dry, ventilated area"
        },
        {
            id: 4,
            name: "POLY VINYL PYROLIDONE K 30",
            category: "Pharmaceutical Raw Materials",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Boai NKY Pharmaceuticals Pvt. Ltd.",
            price: 1250,
            originalPrice: 1450,
            discountPercentage: 14,
            inStock: true,
            stockQuantity: 50,
            description: "Pharmaceutical grade PVP K30 for tablet binding and coating applications.",
            specifications: ["USP Grade", "K-value 27-32", "Pharmaceutical quality"],
            applications: ["Tablet binder", "Film coating", "Suspending agent"],
            shelfLife: "60 months",
            storageConditions: "Store below 25°C in dry conditions"
        },
        {
            id: 5,
            name: "ZINC DIRECT COMPRESS 101/102",
            category: "Pharmaceutical Raw Materials",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Ankit Pulps & Boards Pvt. Ltd./NB Entrepreneurs/Accent Microcell",
            price: 185,
            originalPrice: 220,
            discountPercentage: 16,
            inStock: true,
            stockQuantity: 75,
            description: "Direct compression grade zinc compound for pharmaceutical tablets.",
            specifications: ["DC Grade", "High compressibility", "Pharmaceutical grade"],
            applications: ["Direct compression", "Nutritional supplements", "Pharmaceutical tablets"],
            shelfLife: "36 months",
            storageConditions: "Store in cool, dry place"
        },
        {
            id: 6,
            name: "GELATIN",
            category: "Food Additives",
            packaging: "BAG",
            weight: "50 KG",
            image: "/images/icon_bag.svg",
            manufacturer: "Narmada Gelatines Pvt. Ltd.",
            price: 895,
            originalPrice: 1050,
            discountPercentage: 15,
            inStock: true,
            stockQuantity: 25,
            description: "High-quality edible gelatin for food and pharmaceutical applications.",
            specifications: ["Edible Grade", "Type A", "200 Bloom strength"],
            applications: ["Capsule shells", "Food gelling", "Confectionery"],
            shelfLife: "36 months",
            storageConditions: "Store in cool, dry place below 25°C"
        },
        {
            id: 7,
            name: "MALTO DEXTRINE",
            category: "Food Additives",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Roquette Riddhi Siddhi Pvt. Ltd.",
            price: 125,
            originalPrice: 145,
            discountPercentage: 14,
            inStock: true,
            stockQuantity: 180,
            description: "Food grade maltodextrin for sports nutrition and food processing.",
            specifications: ["Food Grade", "DE 10-15", "White powder"],
            applications: ["Sports drinks", "Food processing", "Instant foods"],
            shelfLife: "24 months",
            storageConditions: "Store in dry, cool place"
        },
        {
            id: 8,
            name: "FERRIC AMMONIUM CITRATE",
            category: "Pharmaceutical Raw Materials",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Shreenath Chemical",
            price: 285,
            originalPrice: 330,
            discountPercentage: 14,
            inStock: true,
            stockQuantity: 90,
            description: "Pharmaceutical grade ferric ammonium citrate for iron supplements.",
            specifications: ["USP Grade", "Iron content 16-21%", "Brown scales"],
            applications: ["Iron supplements", "Pharmaceutical preparations", "Food fortification"],
            shelfLife: "36 months",
            storageConditions: "Store in tightly closed containers"
        },
        {
            id: 9,
            name: "AMMONIUM CHLORIDE",
            category: "Chemical Compounds",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Rasino Herbs Pvt. Ltd.",
            price: 85,
            originalPrice: 98,
            discountPercentage: 13,
            inStock: true,
            stockQuantity: 250,
            description: "Industrial grade ammonium chloride for various applications.",
            specifications: ["Technical Grade", "99% purity", "White crystalline"],
            applications: ["Dry cell batteries", "Flux in soldering", "Fertilizers"],
            shelfLife: "Indefinite",
            storageConditions: "Store in dry place away from moisture"
        },
        {
            id: 10,
            name: "CALCIUM CARBONATE",
            category: "Pharmaceutical Raw Materials",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Suddeep Pharma Pvt. Ltd.",
            price: 45,
            originalPrice: 55,
            discountPercentage: 18,
            inStock: true,
            stockQuantity: 400,
            description: "Pharmaceutical grade calcium carbonate for tablets and supplements.",
            specifications: ["USP Grade", "98% CaCO3", "Fine powder"],
            applications: ["Antacid tablets", "Calcium supplements", "Food fortification"],
            shelfLife: "60 months",
            storageConditions: "Store in dry place"
        },
        {
            id: 11,
            name: "SODIUM CITRATE",
            category: "Food Additives",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Posy Pharmachem Pvt. Ltd.",
            price: 165,
            originalPrice: 190,
            discountPercentage: 13,
            inStock: true,
            stockQuantity: 120,
            description: "Food grade sodium citrate for beverages and pharmaceutical use.",
            specifications: ["Food Grade", "E331", "Dihydrate form"],
            applications: ["Food preservative", "pH buffer", "Anticoagulant"],
            shelfLife: "60 months",
            storageConditions: "Store in cool, dry place"
        },
        {
            id: 12,
            name: "CITRIC ACID",
            category: "Food Additives",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Posy Pharmachem Pvt. Ltd.",
            price: 115,
            originalPrice: 135,
            discountPercentage: 15,
            inStock: true,
            stockQuantity: 200,
            description: "Food grade citric acid for beverages and food processing.",
            specifications: ["Food Grade", "E330", "Monohydrate"],
            applications: ["Food acidulant", "Beverages", "Preservative"],
            shelfLife: "60 months",
            storageConditions: "Store in dry conditions"
        },
        {
            id: 13,
            name: "SODIUM CMC",
            category: "Food Additives",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Posy Pharmachem Pvt. Ltd.",
            price: 385,
            originalPrice: 450,
            discountPercentage: 14,
            inStock: false,
            stockQuantity: 0,
            description: "Sodium carboxymethyl cellulose for food and pharmaceutical applications.",
            specifications: ["Food Grade", "High viscosity", "E466"],
            applications: ["Food thickener", "Tablet disintegrant", "Stabilizer"],
            shelfLife: "36 months",
            storageConditions: "Store in dry, cool place"
        },
        {
            id: 14,
            name: "CAUSTIC SODA",
            category: "Industrial Chemicals",
            packaging: "BAG",
            weight: "50 KG",
            image: "/images/icon_bag.svg",
            manufacturer: "Hindustan Phosphate Pvt. Ltd.",
            price: 65,
            originalPrice: 75,
            discountPercentage: 13,
            inStock: true,
            stockQuantity: 500,
            description: "Industrial grade caustic soda for chemical processing.",
            specifications: ["Technical Grade", "99% NaOH", "Flakes form"],
            applications: ["Chemical processing", "Soap manufacturing", "Water treatment"],
            shelfLife: "Indefinite",
            storageConditions: "Store in dry place, away from moisture"
        },
        {
            id: 15,
            name: "DI CALCIUM PHOSPHATE",
            category: "Pharmaceutical Raw Materials",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Hindustan Phosphate Pvt. Ltd.",
            price: 95,
            originalPrice: 110,
            discountPercentage: 14,
            inStock: true,
            stockQuantity: 150,
            description: "Pharmaceutical grade dicalcium phosphate for tablets and supplements.",
            specifications: ["USP Grade", "Dihydrate form", "White powder"],
            applications: ["Tablet excipient", "Calcium supplements", "Food fortification"],
            shelfLife: "60 months",
            storageConditions: "Store in cool, dry place"
        },
        {
            id: 16,
            name: "XANTHAN GUM",
            category: "Food Additives",
            packaging: "BAG",
            weight: "20 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Jungbunzlauer Austria AG",
            price: 1850,
            originalPrice: 2150,
            discountPercentage: 14,
            inStock: true,
            stockQuantity: 30,
            description: "Food grade xanthan gum for thickening and stabilizing applications.",
            specifications: ["Food Grade", "E415", "High purity"],
            applications: ["Food thickener", "Gluten-free baking", "Sauces"],
            shelfLife: "36 months",
            storageConditions: "Store in cool, dry place"
        },
        {
            id: 17,
            name: "DI SODIUM EDTA",
            category: "Chemical Compounds",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Aditya Chemicals",
            price: 285,
            originalPrice: 325,
            discountPercentage: 12,
            inStock: true,
            stockQuantity: 80,
            description: "Disodium EDTA for pharmaceutical and cosmetic applications.",
            specifications: ["USP Grade", "99% purity", "Dihydrate"],
            applications: ["Chelating agent", "Preservative", "Metal sequestrant"],
            shelfLife: "60 months",
            storageConditions: "Store in dry place"
        },
        {
            id: 18,
            name: "EMPTY HARD GELATIN CAPSULES 0/1/2",
            category: "Pharmaceutical Raw Materials",
            packaging: "BOX",
            weight: "Variable",
            image: "/images/icon_box.svg",
            manufacturer: "Chem Caps Ltd.",
            price: 2850,
            originalPrice: 3200,
            discountPercentage: 11,
            inStock: true,
            stockQuantity: 100,
            description: "Empty hard gelatin capsules for pharmaceutical preparations.",
            specifications: ["Size 0, 1, 2", "Transparent", "Halal certified"],
            applications: ["Pharmaceutical capsules", "Herbal supplements", "Nutraceuticals"],
            shelfLife: "60 months",
            storageConditions: "Store below 25°C, 60% RH"
        },
        {
            id: 19,
            name: "LIGHT KAOLINE",
            category: "Pharmaceutical Raw Materials",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Neelkanth",
            price: 125,
            originalPrice: 145,
            discountPercentage: 14,
            inStock: true,
            stockQuantity: 90,
            description: "Light kaoline for pharmaceutical and cosmetic applications.",
            specifications: ["USP Grade", "Light density", "White powder"],
            applications: ["Pharmaceutical excipient", "Cosmetics", "Antacid preparations"],
            shelfLife: "Indefinite",
            storageConditions: "Store in dry conditions"
        },
        {
            id: 20,
            name: "MAGNESIUM STERATE",
            category: "Pharmaceutical Raw Materials",
            packaging: "BAG",
            weight: "25 KG",
            image: "/images/icon_powder.svg",
            manufacturer: "Nitika Pharmaceuticals Specialities Pvt. Ltd.",
            price: 485,
            originalPrice: 565,
            discountPercentage: 14,
            inStock: true,
            stockQuantity: 60,
            description: "Pharmaceutical grade magnesium stearate as tablet lubricant.",
            specifications: ["USP Grade", "Vegetable source", "Fine powder"],
            applications: ["Tablet lubricant", "Capsule lubricant", "Flow aid"],
            shelfLife: "60 months",
            storageConditions: "Store in cool, dry place"
        },
        {
            id: 21,
            name: "SORBITOL IP",
            category: "Food Additives",
            packaging: "DRUM",
            weight: "300 KG",
            image: "/images/icon_drum.svg",
            manufacturer: "Gujarat Polyols Ltd/Gujarat Ambuja",
            price: 145,
            originalPrice: 165,
            discountPercentage: 12,
            inStock: true,
            stockQuantity: 15,
            description: "Food grade sorbitol for pharmaceutical and food applications.",
            specifications: ["IP Grade", "70% solution", "Clear liquid"],
            applications: ["Sugar substitute", "Humectant", "Tablet coating"],
            shelfLife: "24 months",
            storageConditions: "Store at room temperature"
        },
        {
            id: 22,
            name: "ISO PROPYL ALCOHOL",
            category: "Chemical Compounds",
            packaging: "DRUM",
            weight: "160 KG",
            image: "/images/icon_flask.svg",
            manufacturer: "Reliance Organic",
            price: 95,
            originalPrice: 110,
            discountPercentage: 14,
            inStock: true,
            stockQuantity: 25,
            description: "High purity isopropyl alcohol for pharmaceutical and industrial use.",
            specifications: ["99% purity", "Technical grade", "Clear liquid"],
            applications: ["Disinfectant", "Cleaning agent", "Solvent"],
            shelfLife: "Indefinite",
            storageConditions: "Store in cool, dry place away from ignition sources"
        },
        {
            id: 23,
            name: "METHYLENE CHLORIDE",
            category: "Chemical Compounds",
            packaging: "DRUM",
            weight: "250 KG",
            image: "/images/icon_flask.svg",
            manufacturer: "Gujarat Alkalies & Chemicals Ltd",
            price: 185,
            originalPrice: 215,
            discountPercentage: 14,
            inStock: true,
            stockQuantity: 20,
            description: "High purity methylene chloride for industrial applications.",
            specifications: ["99.5% purity", "Technical grade", "Colorless liquid"],
            applications: ["Solvent", "Paint stripper", "Degreasing agent"],
            shelfLife: "Indefinite",
            storageConditions: "Store in cool, ventilated area"
        },
        {
            id: 24,
            name: "GLYCERIN",
            category: "Food Additives",
            packaging: "DRUM",
            weight: "250 KG",
            image: "/images/icon_flask.svg",
            manufacturer: "Adani Wilmar",
            price: 125,
            originalPrice: 145,
            discountPercentage: 14,
            inStock: true,
            stockQuantity: 30,
            description: "Food grade glycerin for pharmaceutical and cosmetic applications.",
            specifications: ["USP Grade", "99.5% purity", "Clear liquid"],
            applications: ["Humectant", "Sweetener", "Cosmetic ingredient"],
            shelfLife: "60 months",
            storageConditions: "Store at room temperature"
        },
        {
            id: 25,
            name: "PROPYLENE GLYCOL",
            category: "Food Additives",
            packaging: "DRUM",
            weight: "215 KG",
            image: "/images/icon_flask.svg",
            manufacturer: "Manali Petrochemicals Ltd",
            price: 165,
            originalPrice: 190,
            discountPercentage: 13,
            inStock: true,
            stockQuantity: 25,
            description: "Food grade propylene glycol for pharmaceutical applications.",
            specifications: ["USP Grade", "99.5% purity", "Clear liquid"],
            applications: ["Humectant", "Solvent", "Antifreeze"],
            shelfLife: "60 months",
            storageConditions: "Store at room temperature"
        },
        {
            id: 26,
            name: "LIQUID GLUCOSE",
            category: "Food Additives",
            packaging: "DRUM",
            weight: "300 KG",
            image: "/images/icon_drum.svg",
            manufacturer: "Roquette",
            price: 85,
            originalPrice: 98,
            discountPercentage: 13,
            inStock: true,
            stockQuantity: 40,
            description: "Food grade liquid glucose for confectionery and pharmaceutical use.",
            specifications: ["Food Grade", "DE 42", "Clear syrup"],
            applications: ["Confectionery", "Pharmaceuticals", "Food processing"],
            shelfLife: "24 months",
            storageConditions: "Store in cool place"
        }
    ];

    const [products, setProducts] = useState(productsData)

    return (
        <MyContext.Provider value={{ 
            temp, 
            setTemp, 
            products, 
            setProducts,
            categories 
        }}>
            {children}
        </MyContext.Provider>
    )
}

export default Myprovider
